### PR TITLE
autoSelectExchangeTrades correction for message NASDAQ

### PR DESCRIPTION
**Pull request by onnokleen**
For NASDAQ, the message was missing the exchange's name if the exchange indicator is T instead of Q

### CODE REVIEW

**Comment by emilsjoerup** [comment]
Hi Onno, good catch!

I was wondering whether we should put in a toggle to suppress the message? 
```
autoSelectExchangeTrades <- function(tData, noMessage = FALSE) {
...
}
```

Or something like that?

Is this error only present in the trades function and not the quotes one?

**Comment by onnokleen** [comment]
That's true, it's in the quotes-function as well. 

Maybe it's easier just to name it message = TRUE?

**Comment by onnokleen** [comment]
Or maybe printExchange would be more self-explanatory?

**Comment by emilsjoerup** [comment]
You decide :) Both seem fine to me.

**Comment by onnokleen** [comment]
Ok, I will make another pull request then!

**Comment by emilsjoerup** [comment]
Actually, I am pretty sure you can just to your branch and it will get incorporated

**Comment by onnokleen** [comment]
Too late :)

**Comment by onnokleen** [comment]
> Too late :)

It's not too late apparently 👍

**Pull request merged**
