### PR TITLE
autoSelectExchangeTrades group by SYMBOL

### PR DESCRIPTION
**Pull request by onnokleen**
If there is more than one SYMBOL in the data frame, autoSelectExchange should group by SYMBOL. Nothing that is documented or advertised (all example data is only one stock) but better safe than sorry :)

mergeTradesSameTimeStamp already has this safety net. exchangeHoursOnly and salesCondition are by definition not affected.

Maybe it would also be good to rename salesCondition into tradesCondition for the sake of consistency? salesCondition could stay as a shallow function for compatibility?

### CODE REVIEW

**Comment by emilsjoerup** [comment]
I agree re: tradesCondition. Will you add the change to this PR?

BTW the failed checks are expected, I messed up the description and namespace file :)

**Comment by onnokleen** [comment]
> I agree re: tradesCondition. Will you add the change to this PR?
> 
> BTW the failed checks are expected, I messed up the description and namespace file :)

Good to know - I just wanted to ask you via skype^^

**Comment by emilsjoerup** [comment]
I'll commit the reversion that *should* fix it after accepting this PR :)

**Comment by onnokleen** [comment]
I can add the tradesCondition function the next days and will update the PR accordingly. I will let you know when it's done!

**Comment by onnokleen** [comment]
> I'll commit the reversion that _should_ fix it after accepting this PR :)

I am not sure whether I will have time for the PR change today. Hence, don't wait for me. I can change the PR accordingly after your fix.

**Comment by emilsjoerup** [comment]
Pushed the change(s) it shouldn't affect your PR as it pertains to unrelated code.

**Comment by onnokleen** [comment]
> Pushed the change(s) it shouldn't affect your PR as it pertains to unrelated code.

👍

**Comment by onnokleen** [comment]
Now, the tradesCondition function replaces salesCondition. salesCondition is now marked as deprecated.

**Comment by onnokleen** [comment]
Btw.: In the data_handling.R file it is sometimes wasXTS, inputWasXTS, or dummy_was_xts. Should we maybe settle for inputWasXTS?

**Comment by emilsjoerup** [comment]
> Btw.: In the data_handling.R file it is sometimes wasXTS, inputWasXTS, or dummy_was_xts. Should we maybe settle for inputWasXTS?

I think that's a good idea, it's a bit annoying with the inconsistency.

**Pull request merged**
